Repository vtex-apps/category-menu, pull requests merged in 2019-02, with the labels that each got.

#45 Refactor DOM and remove the items number limitation
  CHANGELOG.md
  images/HamburguerIcon.js
  manifest.json
  react/__mocks__/vtex.dreamstore-icons.js
  react/__mocks__/vtex.render-runtime.js
  react/__tests__/__snapshots__/CategoryItem.test.js.snap
  react/__tests__/__snapshots__/CategoryMenu.test.js.snap
  react/categoryMenu.css
  react/components/CategoryItem.js
  react/components/ItemContainer.js
  react/components/SideBar.js
  react/components/SideBarItem.js
  react/index.js
  react/package.json
  react/yarn.lock
Labels: bug, chore

#49 Add menu disposition types on storefront
  CHANGELOG.md
  manifest.json
  messages/en-US.json
  messages/es-AR.json
  messages/pt-BR.json
  react/components/CategoryItem.js
  react/components/ItemContainer.js
  react/index.js
  react/package.json
  react/utils/categoryMenuDisposition.js
Labels: enhancement

#55 Fix alignment of subcategories items
  CHANGELOG.md
  manifest.json
  messages/en-US.json
  messages/es-AR.json
  messages/pt-BR.json
  react/categoryMenu.css
  react/components/CategoryItem.js
  react/components/ItemContainer.js
  react/index.js
  react/utils/categoryMenuPosition.js
Labels: bug

#61 Fix the main overflow
  .prettierrc
  CHANGELOG.md
  manifest.json
  react/__mocks__/vtex.render-runtime.js
  react/__tests__/CategoryItem.test.js
  react/components/CategoryItem.js
  react/components/ItemContainer.js
  react/components/SideBar.js
  react/components/SideBarItem.js
  react/index.js
  react/utils/categoryMenuPosition.js
Labels: bug, enhancement
